### ISSUE TITLE
blender 2.8 support?

### ISSUE THREAD

**Issue by hadaev8** [ross-g/io_pdx_mesh#1]
Maybe it's me, but I can't run it on the latest blender.

**Comment by ross-g** [comment]
Hey, this is already being worked on on a separate branch.
https://github.com/ross-g/io_pdx_mesh/tree/Blender2.8

There are quite a few breaking changes with 2.8 so it's not a simple change. I'm planning for the next update to have two Blender versions you can download (2.79 and 2.80). After that I'll just support one in future.

**Comment by hadaev8** [comment]
Thx

**Comment by Ireheart** [comment]
Can you please note which version of blender this version is for?

**Comment by ross-g** [comment]
The current release version 0.7 supports Blender 2.8 or  newer. https://github.com/ross-g/io_pdx_mesh/commit/be507999af4cf9aa3c4301df87d504e1912e1744
