### ISSUE TITLE
CK3 : blend shape has meshes with vertex count incompatible with base object

### ISSUE THREAD

**Issue by ElTyranos** [ross-g/io_pdx_mesh#14]
Whenever I export a model with "merge vertices" option in blender,  this error messages shows up in the error log.
Yet when I open the .mesh files with blender they have same amount of vertices/edges/faces.

**Comment by ross-g** [comment]
Need a couple more details:
- when you say "this error messages shows up in the error log" I assume you must mean the CK3 error log correct?
- you must be exporting a character mesh correct? as I'm not aware of anything else which uses blendshapes.

If you are trying to export a blendshape or any mesh which uses blendshapes, then you **absolutely** should not be trying to merge vertices. I don't have the Steam version of CK3 yet so can't really do any testing.

**Comment by ElTyranos** [comment]
* Yes I am working on CK3.
* Yes I am working on character meshes (here it was `headgear`)
* I have worked not merging the vertices and it got better.

Yet I still have issues with clothing. Here I have no error message, nothing, the shapes simply don't work.
I use the same workflow as headgear that are working.

Headgear FAT vs NORMAL
![image](https://user-images.githubusercontent.com/6755711/94165178-3c5ea900-fe8a-11ea-8dbe-f5243b10836a.png)
![image](https://user-images.githubusercontent.com/6755711/94165195-3ff23000-fe8a-11ea-93f7-3d24c8df290a.png)

Clothes FAT (left) vs NORMAL (right)
![image](https://user-images.githubusercontent.com/6755711/94164997-03263900-fe8a-11ea-8d04-47c70794f891.png)

NB:
* Why not merging vertices ? Files are 4 times the size.
* Is it possible to export only selected to .mesh ? this avoid "clearing" the blender file from all objects at each export.

**Comment by ElTyranos** [comment]
When I have all my blendshape exported for the above chainmail clothing, no joint vertices, no "vertex count incompatible" error messages, I get this error in the log  :

`[17:35:50][gfx_dx11_pixelbuffer.cpp:178]: D3D error (D:\jenkins\workspace\titus-steam\cw\clausewitz\pdx_gfx2\DX11\gfx_dx11_pixelbuffer.cpp:178): hr returned: Param贲e incorrect.


[17:35:50][gfx_dx11_master_context.cpp:442]: Failed creating pixel buffer
`

It's directly related  to this asset, so there is clearly something wrong.
Shield is combined to the vanilla clothing but I have succeeded similar combination between 2 models already (helmets and mail coif)

**Comment by ElTyranos** [comment]
Ok so it comes from the shield as a shield-less export works. Yet 2 materials blendshapes work on the heads, weird  it does not on bodies.
