### ISSUE TITLE
Mesh exported as blendshape produces D3D error in game: "hr returned: incorrect parameter"

### ISSUE THREAD

**Issue by ElTyranos** [ross-g/io_pdx_mesh#16]
Hello,

I can't tell where this issue comes from, maybe D3D engine, maybe the exporter. I tried to narrow it down as much as I could on my end.

Complete report here that I also sent to PDX : https://github.com/ElTyranos/CommunityFlavorPack/issues/29

Regards,
ElTyranos

**Comment by ross-g** [comment]
Thanks, I will try to take a look at the mesh data for the ones which are causing a problem.

Do you have some source files you don't mind sharing so I can take a look? The CommunityFlavorPack obviously doesn't contain the "broken" blendshape exports, but if you can supply a set of working and broken export files, along with source scenes, then it will make my job a lot easier.

**Comment by ElTyranos** [comment]
[nasal_tribal.zip](https://github.com/ross-g/io_pdx_mesh/files/5436034/nasal_tribal.zip)
[safran_low_reworked.zip](https://github.com/ross-g/io_pdx_mesh/files/5436038/safran_low_reworked.zip)

I hope that will help, ignore if some mesh are still untriangulated, I do it before export.

**Comment by ross-g** [comment]
Thanks, I've grabbed the files and removed the file links as you requested.
Should hopefully get chance to look at this over the next week or two.

**Comment by ElTyranos** [comment]
Thanks ! Feel free to poke me if you need anything.

**Comment by ElTyranos** [comment]
![image](https://user-images.githubusercontent.com/6755711/103248144-b7dc6480-4969-11eb-9e87-210ae073f5f9.png)

Hello,

This is still happening with 0.72.
As you can see on this "bs_muscular"  blendshape, the legs are working properly, the body is returning

```
[00:03:21][pdx_assert.cpp:568]: Assertion failed: hr returned:
Incorrect parameter.
```

and does not switch to the blendshape

Regards,
ElTyranos

**Comment by ElTyranos** [comment]
Doesnt work on blender 2.82 + 0.72  and blender 2.91 +  bugfix branch

**Comment by ross-g** [comment]
Hey @ElTyranos, just to let you know I'm still looking at this and trying to narrow down the problem before implementing a solve. The files you supplied last time are a great help, but it's a complex issue and not a clear "thing I'm doing wrong" (as shown with some parts working and others not).

So, sorry this is not a fast solve. Thanks for being patient. I am **actively** looking at the problem when I get free time.

Cheers!

**Comment by ElTyranos** [comment]
Hey Ross,

Thanks for reaching out to me and of course I am glad to hear you're still trying to fix that. No worries tho, I know those are not easy tasks. Meanwhile I manage to limit what characters use what models to avoid the clipping too much, but people started to notice and whine because of the clothing (I don't want to hold my models either).

Don't hesitate to poke me if you need more files to analyse or options to test out at large scale. On my end, just from experience and feelings, I tend to believe it's somewhat linked to the vertices count. The higher it is the more likely it will fail the export. Very low poly models never failed, AFAIK.

Good luck with all that.
Regards,
ElT

**Comment by ross-g** [comment]
@ElTyranos and anyone watching this issue in the hopes of a fix... you can download from the bugfixes branch now and (hopefully) you problems will be solved.

Instructions on how to do that are here: https://github.com/ross-g/io_pdx_mesh/issues/24#issuecomment-741078033
