### ISSUE TITLE
CK3 select_all Error

### ISSUE THREAD

**Issue by zumbak04** [ross-g/io_pdx_mesh#17]
I was playing around loading and exporting CK3 vanilla models for testing purposes when I came across a problem.
<details>
<summary>Errors</summary>

```
Operator bpy.ops.object.select_all.poll() failed, context is incorrect
Traceback (most recent call last):
  File "C:\Users\zumba\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 516, in execute
    merge_verts=self.chk_merge
  File "C:\Users\zumba\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1245, in export_meshfile
    bpy.ops.object.select_all(action='DESELECT')
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

location: <unknown location>:-1
```
![image](https://user-images.githubusercontent.com/46384992/98468426-cb820f00-21f3-11eb-9489-53ab7448f0c4.png)

</details>
I was able to load this model and export without problems yesterday, but these errors appeared today and I have no idea why.

<details>
<summary>Model Itself and Interface</summary>

![image](https://user-images.githubusercontent.com/46384992/98468460-f79d9000-21f3-11eb-81e6-9dd9031b5c27.png)

</details>

I'll attach meshes I'm trying to export.
[prophet_shield.zip](https://github.com/ross-g/io_pdx_mesh/files/5506539/prophet_shield.zip)

**Comment by ross-g** [comment]
Hey, thanks for the detailed report! This is just a small bug which I have now fixed. You just need to make sure you export in "Object" mode and not in "Edit Mesh" mode.

**Comment by ross-g** [comment]
This is now fixed in the newest release. (https://github.com/ross-g/io_pdx_mesh/commit/2af4c48320d0a7d213915b3ea7e0d9e07f1a7abb)
