### ISSUE TITLE
v0.71 - Stellaris: Bone linked locator import fails

### ISSUE THREAD

**Issue by Fragjacker** [ross-g/io_pdx_mesh#22]
Greetings!

In the latest version 0.71 of the importer tools the export/import of locator objects fails. Whenever I parent a locator to a bone, export and re-import it, I get this error:

![image](https://user-images.githubusercontent.com/19975052/99883818-148d8680-2c2a-11eb-8438-9f673bae0c07.png)

On top of this it also seems to not work in-game either as it is supposed to. Locators without bone linkage work just fine. It appears that this bug was introduced with the most recent build. To confirm this theory, I imported a mesh, which I exported with version 0.7, which it properly imported all locators as it should be. I have uploaded both working and failing meshes below for you to test as well:

[Test_meshes.zip](https://github.com/ross-g/io_pdx_mesh/files/5578113/Test_meshes.zip)

I hope this issue can be resolved fast, since it busts bone linked locators for good right now 😁 .

**Comment by ross-g** [comment]
Thanks for raising this one, it's appreciated. That was definitely my fault! 
Happily this was a simple fix (5ed1bee8e10af2744835c09f2afc083bf2ca3b4e) and I've pushed another release to correct this mistake as it was quite a serious one.
