### ISSUE TITLE
Allow exports without a mesh, ie bones & locators only (eg Stellaris ship frames)

### ISSUE THREAD

**Issue by Nevla1** [ross-g/io_pdx_mesh#25]
Hey Ross,

A friend and I have been trying to make custom models and animations for Stellaris mods using your plugin, but we keep running into a wall. There are .mesh files with "frame" in them and upon importing they look something like this (depending on which one, in this case a mammalian battleship frame):

![Screenshot (138)](https://user-images.githubusercontent.com/51030183/102415457-0cb4ce00-3fad-11eb-9f2e-378a00a48487.png)

These frames are required to make new models and animations, but exporting them (or creating them) has proved difficult. We keep getting this error when we try to export:

![Screenshot (139)](https://user-images.githubusercontent.com/51030183/102415653-6a491a80-3fad-11eb-9e5b-d30dec68e7ea.png)

There is a way to do this as other modders in the community have made models and animations, and I believe there is just a setting we are missing. Any help would be appreciated!

Thank you.

**Comment by ross-g** [comment]
Yes this is a limitation of the current exporter. Basically it just expects you to always have a mesh to export... and so exports with bones/locators only will error.

Like with issue #23 the tool just needs a slight rework to support doing this, as it wasn't designed to do that originally. But you are right that this is needed to support the frame type meshes used in Stellaris.

**Comment by mithrils495** [comment]
Hey Ross, I'm also interested in this enhancement if you could do it!

**Comment by ross-g** [comment]
Already in progress! :wink:

**Comment by ross-g** [comment]
Implemented in 0.8 release. (364800cff10bdc822429ec73149cadcb05ef9710)
