### ISSUE TITLE
Blender not allowing me to enable the add-on

### ISSUE THREAD

**Issue by CooperBraun** [ross-g/io_pdx_mesh#27]
Hey mate, not too familiar with this stuff myself but I have been running into this error every time I try to enable the addon for blender after installing the zip file. 

![image](https://user-images.githubusercontent.com/52896862/102850687-230bcf80-446e-11eb-91be-bb90e384c8e9.png)

**Comment by Tetrino** [comment]
The addon as released doesn't work in anything past 2.9.0 - but if you download the version off the bugfix branch via the "clone and download" option as a .zip that will run fine in 2.91 + 2.92.

**Comment by CooperBraun** [comment]
Thanks mate! Working perfectly now!
