### ISSUE TITLE
Maya 2020 exporting error

### ISSUE THREAD

**Issue by mithrils495** [ross-g/io_pdx_mesh#31]
Hey Ross, love your tool first of all!

I have an error using the tool for Maya while exporting. It goes:

" Mesh export failed! ... Maya Node does not exist (or is not unique):: u'None' "

I'm using Maya 2020, I have a friend who uses an older version of Maya and it works for him. Do you know the specific problem with this?

**Comment by ross-g** [comment]
You'll have to give me a little more info to go on or zip and upload your Maya scene I'm afraid!

The error you've gotten is saying that the exporter is trying to process something but has found that it actually doesn't exist. The message by itself isn't very helpful.

If you open the Script Editor in Maya it will give you much more detailed output, including which lines of my code the error is coming from etc... (_Menu bar: Windows > General Editors > Script Editor_) If you can get me that output then I can look at the problem. But you are correct that I've not tested in Maya 2020, I only have 2015 and 2018 personally though I can probably test at work.

**Comment by mithrils495** [comment]
I'll see what other info I can provide to help. I downloaded Maya 2019 and it works fine, so I suspect is an issue with Maya version. Thanks for the reply.

**Comment by Orthanc6** [comment]
Getting the same error in Maya 2020. Only for animation export, mesh export is working fine!

here's what the script editor is showing:


// Result: H:/Autodesk/projects/Stellaris/Star Wars/Death_Star/Death_Star.ma // 
[io_pdx_mesh] INFO:  exporting H:/Autodesk/projects/Stellaris/Star Wars/Death_Star/st_empire_01_colossus_opening.anim
[io_pdx_mesh] INFO:  writing animation info -
[io_pdx_mesh] WARNING:  FAILED to export H:/Autodesk/projects/Stellaris/Star Wars/Death_Star/st_empire_01_colossus_opening.anim
[io_pdx_mesh] ERROR:  Maya Node does not exist (or is not unique):: u'None'
# Traceback (most recent call last):
#   File "C:/Users/Stephen/Documents/maya/scripts\io_pdx_mesh\pdx_maya\maya_ui.py", line 566, in export_anim
#     export_animfile(anim_filepath, **options)
#   File "C:/Users/Stephen/Documents/maya/scripts\io_pdx_mesh\pdx_maya\maya_import_export.py", line 1704, in export_animfile
#     export_bones = get_skeleton_hierarchy([root_bone])
#   File "C:/Users/Stephen/Documents/maya/scripts\io_pdx_mesh\pdx_maya\maya_import_export.py", line 639, in get_skeleton_hierarchy
#     root_bone.add(get_root(bone.name()))
#   File "H:\Autodesk\Maya2020\Python\lib\site-packages\pymel\core\nodetypes.py", line 1436, in name
#     name = self._updateName(long)
#   File "H:\Autodesk\Maya2020\Python\lib\site-packages\pymel\core\nodetypes.py", line 1323, in _updateName
#     raise general.MayaNodeError
# pymel.core.general.MayaNodeError: Maya Node does not exist (or is not unique):: u'None'

**Comment by ross-g** [comment]
Thanks for the info, is there any chance you could get me access to your Maya scene file for this so I can look at where it's going wrong? 

Unfortunately this looks like a Maya code error that I might have to work around. (ie `bone.name()` should not return `None` and I would need to look at your scene to check why that happens)

**Comment by Orthanc6** [comment]
Here's the file:
https://drive.google.com/file/d/1ywlUhyLhJMOqKKLHruTzeo4GwLCJX3yA/view?usp=sharing
