### ISSUE TITLE
Cant install to blender correctly

### ISSUE THREAD

**Issue by TheBarbarossa** [ross-g/io_pdx_mesh#34]
Hey there, hopefully your still responding to people on here, been trying to get into eu4 modding and was attempting to install this for Blender. Everytime i add it to my Add-ons it comes up with this message when i attempt to check the box. 

![image](https://user-images.githubusercontent.com/77446888/104599773-1abf4280-5670-11eb-919a-5a6b26a46c3b.png)

![image](https://user-images.githubusercontent.com/77446888/104599735-0da25380-5670-11eb-8fe4-4bd7f148a829.png)

No idea how to fix this and it would be amazing if you could push me in the right direction. Thanks :)

**Comment by ross-g** [comment]
Hey @TheBarbarossa this has been reported and fixed already. 😄 

If you check the comments for #24 there are some instructions and a link to the work-in-progress bugfixes version of the tool that you can download and use temporarily.
