### ISSUE TITLE
Error in addon_utils.py

### ISSUE THREAD

**Issue by smigglethesniper** [ross-g/io_pdx_mesh#35]
<img width="712" alt="Screen Shot 2021-01-25 at 11 37 10" src="https://user-images.githubusercontent.com/54944292/105701251-eebe7f80-5f01-11eb-892b-b91f37dfe27e.png">

**Comment by ross-g** [comment]
Hey @smigglethesniper this has been reported and fixed already. 😄

If you check the comments for #24 there are some instructions and a link to the work-in-progress bugfixes version of the tool that you can download and use temporarily.
