### ISSUE TITLE
Import Error on Older Stellaris Portraits

### ISSUE THREAD

**Issue by Blanclour** [ross-g/io_pdx_mesh#4]
![importerror](https://user-images.githubusercontent.com/2582909/68888026-bf966680-06df-11ea-867e-65a2ca8a1833.png)

The newest lithoids portrait pack imports just fine, but all older portraits in the game give this error.

**Comment by ross-g** [comment]
Hey, thanks for the post. Happily this is something already fixed (with [this commit](https://github.com/ross-g/io_pdx_mesh/commit/5d45a4f492f15f03e600342fa665386146757f5e)).

You can either grab a copy of the bugfixes branch here on Github or wait for the next release. I'm just making the addon compatible with Blender 2.8 before doing another release with fixes etc.
