### ISSUE TITLE
Mesh Limit

### ISSUE THREAD

**Issue by Avatar1987** [ross-g/io_pdx_mesh#42]
Hey Ross,

is there some sort of mesh limit loading into blender ?

the .mesh file hast  116 meshes and load ingame fine, but if i try to load it into blender it only loads 100 meshes.

**Comment by ross-g** [comment]
I'd be interested to see the file or check if there are errors on importing which stop/skip meshes being created.

I've just tested and exported 225 meshes from Blender, they all imported back again as expected.

**Comment by Avatar1987** [comment]
![image](https://user-images.githubusercontent.com/30906293/110850738-6ed15680-82b0-11eb-9581-327410994194.png)

**Comment by ross-g** [comment]
Yeah that file has broken normals then, you won't be able to import it as it is.

Was it my tool that exported this file originally, where did it come from and do you have the source file that created the bad export? If so I can look into what happened.

**Comment by Avatar1987** [comment]
I guess its a problem with Jorodox then, i started today to export with your tool and it works fine. Jorodox even mirrored meshes etc. its just a broken tool.

**Comment by ross-g** [comment]
Thanks for letting me know, afraid I never tried Jorodox but happy to hear it's working fine with my own tool.
