### ISSUE TITLE
Blender 2.8 bone import fails

### ISSUE THREAD

**Issue by Yandalf** [ross-g/io_pdx_mesh#43]
When trying to import ship frame meshes in Blender 2.8 from Stellaris the import fails, throwing the following message.
![image](https://user-images.githubusercontent.com/22955101/110939346-8c94cf00-8335-11eb-856d-698dca089bda.png)
Without these, no bones get added to the scene meaning animations cannot be imported either.
Plugin version used: 0.8

**Comment by ross-g** [comment]
Blender 2.8 is too old and is no longer supported by the tool, you need to use a newer version.

You are actually warned about this when you enable the addon 😉 
![image](https://user-images.githubusercontent.com/9258768/110943781-83a2fe00-8333-11eb-8b2d-13f28f558e6f.png)

**Comment by Yandalf** [comment]
My bad, sorry!
