### ISSUE TITLE
Addon does not deregister correctly - Blender 2.92.0

### ISSUE THREAD

**Issue by Musketmarine** [ross-g/io_pdx_mesh#44]
![image](https://user-images.githubusercontent.com/26862742/111097540-c1f51480-850f-11eb-9543-02f83decd8bf.png)

Not sure what is going wrong here, but I can't seem to be able to deploy and use the latest version of the plugin. I installed it, and I am unable to enable it.

**Comment by ross-g** [comment]
So I can enable the addon fine in 2.92 the first time I try, meaning the tool should be usable.

The error only occurs for me if I disable the addon and then try to enable it again a second time, which seems to indicate the addon is not deregistering correctly. But if you restart Blender and then try once (and only once) the addon should enable correctly.

**Comment by Musketmarine** [comment]
Gah, that's embarassing, it worked when I restarted like you said. Thanks for the help!

(Not sure if I should close this or not, but atleast something productive came out of this)

**Comment by ross-g** [comment]
No it's cool, it's legitimately a problem! Happily just not one that should stop anyone from using it.

**Comment by oxygenes** [comment]
Hi, i use portable blender, during instalation of addon was in my profile created directory "io_pdx_mesh-0.8" and enabling addon failed. Helped manualy renamed to "io_pdx_mesh".

**Comment by ross-g** [comment]
@oxygenes I think you incorrectly clicked to download the source code and not the release file. The readme instructions on the front page should make this clear.
> Click here to view the [latest relase](https://github.com/ross-g/io_pdx_mesh/releases/latest) and download the io_pdx_mesh.zip file

So this is the link to download from.
![image](https://user-images.githubusercontent.com/9258768/120178340-544cb080-c201-11eb-956b-3b7cf92df0dd.png)

**Comment by oxygenes** [comment]
ya, i downloaded both, then used source by mistake. positive is, that i was forced look into more deeply. :)
