### ISSUE TITLE
Blender environment and UI quirks on Linux

### ISSUE THREAD

**Issue by mk-fg** [ross-g/io_pdx_mesh#45]
Hi,

Haven't used blender for years, and wanted to check if I can tweak some broken mod meshes using this addon.
Immediately bumped into a couple issues enabling it and seemingly bogus/outdated info in the README.
Both issues are with completely default Blender 2.91, running with no initial settings dir.

- Issue when trying to enable it - `NotImplementedError: Running from unknown environment "/usr/bin/python3.9"`.

  Not sure why it's not set to "blender" here (Arch Linux, Blender 2.91.2), but maybe instead of NotImplementedError, addon can try importing either of the top-level blender/maya modules and only raise that with ImportError on both?
  Can be a local issue too, but wanted to report jic it might not be.

- README - there's no such thing as "Tool Shelf".

  Closest that "View" menu has is "Toolbar" and that's NOT where this addon should be found!
  It's under "Sidebar", which indeed is not enabled in blender by default.
  Same as above, not a habitual blender user, so maybe instructions in the README make more sense in some other presumably-more-common non-default/non-linux configuration of blender.
  But if not, maybe README should be updated to at least point in the right direction, instead of kinda away from it :)

Thought to record a quick video of the install/first-use process here, to show it looks here, in case none of the above applies to some different testing setup that you're using: https://e.var.nz/2021-03-18.blender-io_pdx_mesh-quirks.mp4

Cheers!

**Comment by ross-g** [comment]
Yep that's a fair catch, the Blender terminology for that panel changed from 2.8 onwards. It was formerly called the [`Tool Shelf`](https://docs.blender.org/manual/en/2.79/interface/window_system/tabs_panels.html) and is now the `Sidebar`.

I will look at changing the addon registration code, it seems that Blender on Linux uses the system interpreter rather than bundling one with Blender.
