### ISSUE TITLE
Issue with  unigine agent

### ISSUE THREAD

**Issue by Osoru-gansorok** [ross-g/io_pdx_mesh#47]
Python: Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 374, in execute
    bonespace=self.chk_bonespace,
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1177, in import_meshfile
    asset_elem = pdx_data.read_meshfile(meshpath)
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_pdx_mesh\pdx_data.py", line 241, in read_meshfile
    raise NotImplementedError("Unknown file header. {}".format(header))
NotImplementedError: Unknown file header. (b'm', b's', b'1', b'1')

location: <unknown location>:-1

**Comment by ross-g** [comment]
You've not given me any useful information to go on at all... I can see you're trying to import a mesh file though.

What do you mean "issue with unigine agent"?
If you're referring to the game engine Unigine, then you are using the wrong Blender addon. This is for files from the Clausewitz Engine used in Paradox Development Studios strategy game titles. 😄

**Comment by Osoru-gansorok** [comment]
excuse me
When i try to import mesh , it fails may be because it's not a paradox mesh
I follow some tips from this link https://steamcommunity.com/app/365670/discussions/0/1700541698699752868/ about importing .mesh file in blender.
I don't know there was so many differents types for .mesh,
Jorodox a chrome extension to converte file,  leads me to finding pdx-mesh importer because it recognizes my mesh like that
![Captureorodox](https://user-images.githubusercontent.com/58999097/112702054-ac191500-8e68-11eb-8bcf-db49f1e18315.PNG)
agent.mesh came from this link 
https://developer.unigine.com/forum/topic/6669-solved-changing-to-different-animations/

Thank you for your answer

**Comment by ross-g** [comment]
Ah I see the misunderstanding now. Yes a .mesh file extension is not unique to Unigine or to PDX games, it seems to be quite common across several engines. My addon will only work for Paradox .mesh files that are designed to work with the Clausewitz engine.

So good luck, I hope you find another addon for working with Unigine!
