### ISSUE TITLE
Addons refuse to be added to Blender (2.83 through 2.92)

### ISSUE THREAD

**Issue by d-roes** [ross-g/io_pdx_mesh#56]
![Blender Info Log 7_25_2021 8_52_07 AM](https://user-images.githubusercontent.com/87942066/126905267-bdf9bbef-ef22-4f12-90cf-40318603878e.png)

This is what happens when I try to install the Blender addons.

**Comment by ross-g** [comment]
I think you are installing it incorrectly, as that log shows the wrong file being installed from and you have also download the code directly not the [released zip file](https://github.com/ross-g/io_pdx_mesh/releases/latest).

Please try following the [instructions on the front page](https://github.com/ross-g/io_pdx_mesh#setup-for-blender-283), they do work! 😄 
eg installing from scratch using the zip and I get:
`Modules Installed (io_pdx_mesh) from 'D:\\Downloads\\io_pdx_mesh.zip' into 'C:\\Users\\Ross\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons'`
