### ISSUE TITLE
Bug on Blender install

### ISSUE THREAD

**Issue by F1r3Pr1nc3** [ross-g/io_pdx_mesh#58]
I've followed the instruction, I'm using Blender 2.92 Win64 (onWin7).
![BlenderAddonError](https://user-images.githubusercontent.com/61938168/131528616-eccadee7-c53c-4716-804c-fe03d609d5df.PNG)

**Comment by ross-g** [comment]
This looks like it might be the same problem as #44

First, could you make sure you only have it installed once. Restart Blender and then try once (and only once) to enable the addon. Let me know if this doesn't work.
