### ISSUE TITLE
Mesh.calc_tangents(): required parameter "uvmap" to be a keyword argument!

### ISSUE THREAD

**Issue by Menzex** [ross-g/io_pdx_mesh#6]
Mesh.calc_tangents(): required parameter "uvmap" to be a keyword argument!
What can I do to deal with it? I really want to export something but I just can't understand what the debug meaning QWQ

**Comment by ross-g** [comment]
It means that you're trying to use the Blender 2.8 version before I released it ... bugs should be expected!

As it happens, this bug was already fixed in 807550a6b2b5d9ffe1673d4e61c237f05397642c just two days ago.
