### ISSUE TITLE
Shading Issue when exporting mesh with non triangle faces

### ISSUE THREAD

**Issue by Wolfgang-IX** [ross-g/io_pdx_mesh#65]
![image](https://user-images.githubusercontent.com/47208316/153470532-0728cfbb-c76e-45bd-a3f9-17998d627d88.png)

Export setting
![image](https://user-images.githubusercontent.com/47208316/153471255-24d2fbec-d731-4f7a-8429-ec0e70aecbdd.png)

Material
![image](https://user-images.githubusercontent.com/47208316/153471287-2cd2bf79-2eb4-4064-b2e1-077275ce3b20.png)

Exported mesh
https://drive.google.com/drive/folders/1gwL0qEASaRv-uXIMqkGuj7H7nbTWUL8y?usp=sharing

**Comment by ross-g** [comment]
Thanks. This was already fixed by b214cb7005f694557ec943b98ef15380352299ad last year in the bugfix branch.
Should be releasing a new version soon.

**Comment by Wolfgang-IX** [comment]
alright, thanks
