### ISSUE TITLE
Vertex ordering changes on export

### ISSUE THREAD

**Issue by Rewinged** [ross-g/io_pdx_mesh#7]
It seems like vertex ordering changes slightly when you export and import back in. The first vert (0) starts at the correct location but the numbering seems to follow different orders around each quad.
This makes custom blendshapes impossible as parts of the mesh (mostly noticable around UV seams and mesh edges) are offset due to the incorrect vert order.

It would be very very usaeful for Imperator and future games since a lot of portrait stuff relies on blendshapes such as clothing/beards, you are required to make blendshape versions of these meshes in order for them to fit onto characters with differing body/head shapes.

More info and pics are on the imperator modding coop gfx channel

**Comment by ross-g** [comment]
Hey, if you can upload some example files (Maya (.ma) or Blender scenes please) that would be super helpful in checking out what is going on here.

I would expect some vertex ordering to change depending on how the mesh is split up (UV seams, materials etc). So it might be a case of making sure that is always consistent.

**Comment by ross-g** [comment]
This is confirmed fixed in the 0.7 release.
