### ISSUE TITLE
Blender environment not detected on Linux

### ISSUE THREAD

**Issue by freemouser** [ross-g/io_pdx_mesh#70]
Hi, I tried to load this plugin in Blender on Manjaro Linux but it returns a "Running from unknown environment" error.

After experimenting a little with the code I noticed: environment = sys.executable.lower() was returning "/usr/bin/python3.10". This seems to throw off the environmental detection which looks like it expects either "blender" or "maya" as a result.

I did manage to fix it on my system by replacing that line (48) in __init__.py with:
`import os`
`import psutil`
`environment = ""`
`environment = psutil.Process(os.getpid()).name()`
`print("PEEK: environment = ", environment.lower())`

Not sure if this helps anybody running into the same issue.

**Comment by ross-g** [comment]
Thanks for the report 👍  this was brought up previously in #45 and has already been fixed in the Bugfixes branch.

Please download and use that version ahead of it being properly released.

**Comment by freemouser** [comment]
Cheers ross!
