### ISSUE TITLE
mesh export wrong result

### ISSUE THREAD

**Issue by Avatar1987** [ross-g/io_pdx_mesh#71]
the result after exporting does not correspond to the same properties

it behaves as if "Split all vertices" is enabled

from an object with ~30k vertices, an object with ~170k vertices is created

there are no modifiers on the objects

**Comment by ross-g** [comment]
This is completely normal depending on the other qualities of your mesh. On export vertices are split along UV seams, hard edge Normals and Material boundaries.

See Discussion https://github.com/ross-g/io_pdx_mesh/discussions/66 for an example.

Exporting is not the same as Saving, you should expect the file that is exported to have changed as it's being prepared for the game engine to render.

**Comment by Avatar1987** [comment]
yeah we figured out it only happens with flat shading not with smooth shading
