### ISSUE TITLE
can't activate blender add-on

### ISSUE THREAD

**Issue by demonsurvival** [ross-g/io_pdx_mesh#72]
when i try to click the check mark i get this:
![Screenshot from 2022-08-28 18-49-18](https://user-images.githubusercontent.com/69975161/187085563-84a6850f-259a-4dc6-a73c-9ddfc643513a.png)

**Comment by ejdirsel** [comment]
having the same exact problem

**Comment by ross-g** [comment]
Thanks for the report 👍 this was brought up previously in #45 and has been fixed in the Bugfixes branch. Please download and use that version ahead of it being properly released ([instructions here](https://github.com/ross-g/io_pdx_mesh/wiki/Setup-and-installation#bugfixes-branch)).
