### ISSUE TITLE
no mesh in "PDX meshes:"

### ISSUE THREAD

**Issue by Nohttt** [ross-g/io_pdx_mesh#76]
![image](https://user-images.githubusercontent.com/102611220/215290202-ab95053a-1bbe-4bfc-a205-e636279438c9.png)
how to add mesh in this menu

**Comment by ross-g** [comment]
Only meshes with a "PDX material" assigned will show up.

You need to create materials with the addon and apply them to a mesh for it to be valid to export. Meshes without such a material are ignored.
