### ISSUE TITLE
Unknown data type error when exporting

### ISSUE THREAD

**Issue by jagyCZ** [ross-g/io_pdx_mesh#84]
**Describe the bug**
Unable to export mesh due to Unknown data type error

1. Make model
2. Create PDX material (pdx mesh advanced)
3. Assign textures
4. Try to export mesh and fail

 - OS: Windows
 - Modelling app: Blender 3.6.1

Addon set-up for HOI4
Error log attached

[error.txt](https://github.com/ross-g/io_pdx_mesh/files/12255627/error.txt)

**Comment by ross-g** [comment]
From your error log it looks like the shader is the problem. `MAhangar_flight` ?

Did you assign the PDX material you've created to the mesh you are trying to export? If so then you might have to upload the Blender scene for me to have a look at, as this seems to be a setup error but I can't rule out that Blender might have changed something in an update.

**Comment by jagyCZ** [comment]
After I made the mesh, I made a new material with the PDX mesh tools, I plugged in textures in the shading tab and tried exporting the mesh. Thats where the error occured

**Comment by jagyCZ** [comment]
Ok, so I have found out what the problem is.
When I create material with your tools, custom property for the material is created, property type is "string" with property name "shader" and value "PdxMeshAdvanced" or whatever I choose at the creation. For some to me unknown reason, the property type changed from "string" to "python" and the value changed from "PdxMeshAdvanced" to "{}". To be clear, I never touched any of this stuff, and it must have happened somehow on it's own.

**Comment by ross-g** [comment]
Thanks for helping narrow this down, I will check this out in newer versions of Blender to see if something changed.

**Comment by ross-g** [comment]
I've tried to repro this with Blender 3.6 but not been able to, I don't think the addon is at fault here but I've added this into the list of "error messages which need to be user readable".
