### ISSUE TITLE
Imperator model with empty. Scaling issue in roundtrip.

### ISSUE THREAD

**Issue by MattTheLegoman** [ross-g/io_pdx_mesh#9]
G'day, here's the issue that I found when importing and exporting an Imperator:Rome model.

This is the issue in the screenshot. After importing and exporting this port, the ship docked in the port is oversized (ship to the right). They should be small and visually fit inside the tiny port model (the port model is to the right of the big ship).

![20200128133753_1](https://user-images.githubusercontent.com/5894960/73241325-ae3c0100-41dc-11ea-86de-13469420a9c7.jpg)

Here are the steps that I took.
1. Import the game model gfx\models\buildings\eastern_port\eastern_port.mesh

2. With no changes or edits, export the file, overwriting the game model.

3. In game the ships docked in the Eastern Port are oversized.

This issue also occurs with a custom model, created in Blender with either a copy of the ship_locator empty or a new empty named ship_locator.

I have attached the .blend file of the imported eastern_port model. I can also attach the complete folder with the textures and .mesh or my custom model (Carthage Great Harbour). 
[Eastern Port.zip](https://github.com/ross-g/io_pdx_mesh/files/4120967/Eastern.Port.zip)

**Comment by ross-g** [comment]
Thanks for posting an informative bug report! 10/10
I saw your post on Discord too and I will definitely look at this over the weekend.

Hopefully it should be something reasonably simple to diagnose, as a I don't have Imperator I can't do any in-game testing.

**Comment by MattTheLegoman** [comment]
Thanks ross-g, I have GitHub Desktop to update the add-on and can test in-game.

**Comment by MattTheLegoman** [comment]
G'day, I still have this issue.

I believe that the transform of the locator (x, y ,z coordinates) is in the correct position. However, the scale of the locator is wrong.

I have been looking at this issue for a while now, months and I admit that it boggles me so I apologise if I am not being clear

![859580_20200429233851_1](https://user-images.githubusercontent.com/5894960/80618246-ad359c80-8a75-11ea-92d5-df1756c813c7.png)

**Comment by ross-g** [comment]
This is now fixed in the newest release. (https://github.com/ross-g/io_pdx_mesh/commit/2af4c48320d0a7d213915b3ea7e0d9e07f1a7abb)
