### ISSUE TITLE
Error when creating a PDX material in Blender

### ISSUE THREAD

**Issue by tombricks** [ross-g/io_pdx_mesh#91]
**Describe the bug**
When trying to create a PDX material, this error appears.

**To Reproduce**
1. Go to Create a PDX material
2. Click on OK
3. See error

**Software (please complete the following information):**
 - OS: Windows
 - Modelling app: Blender

**Screenshots**
![image](https://github.com/ross-g/io_pdx_mesh/assets/22965682/3fdcd52a-6b90-481d-ab03-6711a82e35af)
![image](https://github.com/ross-g/io_pdx_mesh/assets/22965682/82a84e23-028d-4cd5-aeb0-602ec9aa8fdc)

**Comment by ross-g** [comment]
Duplicate of #86
