### ISSUE TITLE
Blender 4.1 No Longer Supports mesh.use_auto_smooth - Temp Fix Attached

### ISSUE THREAD

**Issue by Tetrino** [ross-g/io_pdx_mesh#92]
Blender no longer supports the Auto Smooth attribute on meshes. 

It now assumes behaviour as if Auto Smooth is on all meshes with a value of 180 degrees, as seen here: https://developer.blender.org/docs/release_notes/4.1/modeling/#auto-smooth

Without temporarily removing two lines of code as here, there is an error on import: https://github.com/Tetrino/io_pdx_mesh/commit/5d7827d493e7a966907d586e3799d1704445039f 

I have created a convenience PR (#93 ) for anyone who wishes to use it, however this fix is a hack and should never make it to main.

**Comment by ross-g** [comment]
Thanks for putting this up!
I've finally gotten around to fixing this in 2249e35f80a1cc04ba4c2b8e4c650f36b18085db and releasing in 0.91
