### ISSUE TITLE
Cant enable on Blender 3.3

### ISSUE THREAD

**Issue by thedotdesertfox** [ross-g/io_pdx_mesh#96]
![image](https://github.com/user-attachments/assets/ab73a22d-9561-441b-925e-78697b42eb7e)
This is the error message i get when trying to enable it.

**Comment by ross-g** [comment]
I suspect you have possibly installed it wrong somehow based on that error message, or you have tried to install it twice and it numbered one of the folders.

Did you use `Install Add-on from file` and select the zip file you have downloaded?

**Comment by thedotdesertfox** [comment]
So I had accidentally tried to install using an unziped version of the folder, but i thought nothing happened so I retried using the zip file itself

**Comment by ross-g** [comment]
Assuming you've not changed the default addons installation directory, have a look inside `%AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons` and (with Blender closed) delete any folders for this addon. Then install from the zip again.

**Comment by thedotdesertfox** [comment]
I tried that and it gives the same error.

**Comment by ross-g** [comment]
What does it look like in your addon preferences?
eg
![image](https://github.com/user-attachments/assets/af77cdb7-76a6-4600-826b-b2090b20ab59)

**Comment by thedotdesertfox** [comment]
![image](https://github.com/user-attachments/assets/08f23966-689a-4255-800b-8c92de34cdd8)
this

**Comment by thedotdesertfox** [comment]
It is quite shocking how good i am at having problems at every step of the hoi4 modding process :)

**Comment by ross-g** [comment]
Rename the folder listed there from `io_pdx_mesh-0.9` to just `io_pdx_mesh`

**Comment by thedotdesertfox** [comment]
in blender or the file explorer?

**Comment by thedotdesertfox** [comment]
ok i was able to enable it although im not sure it works, as i dont have the option to import a .mesh file
