### ISSUE TITLE
Exporting an animation, and then importing it back compresses the armature

### ISSUE THREAD

**Issue by nevadaa** [ross-g/io_pdx_mesh#97]
**Describe the bug**
Exporting a .anim file and then importing it back to the exact same model compresses the armature, not scaling it but simply pressing the bones together

**To Reproduce**
1. Make a keyframed animation (regardless whether or not you bake it)
2. Export it as a .anim with any options
3. Import the .anim back to the exact same model, or even importing the same mesh that's been exported prior
4. Skeleton compresses itself

**Software (please complete the following information):**
 - OS: Linux
 - Modelling app: Blender

**Additional context**

**Screenshots**

https://github.com/user-attachments/assets/f7df1e53-76dc-4e28-89cc-0d47fd83a275

**Comment by ross-g** [comment]
As you self closed this issue, did you figure it out? I can't reproduce any problem with the vanilla content or with building my own skeleton so I assume it might be scene setup related.

**Comment by nevadaa** [comment]
Hey! Thanks for the fast reply. The problem was to do with transforms in the scene, yeah. Thankfully I've got it sorted.
